kind: pipeline
type: docker
name: checks

trigger:
  event:
    - push
    - pull_request
    - cron

steps:
  - name: Run checks
    image: nixpkgs/nix-flakes:nixos-22.05
    commands:
      - nix develop --command cargo fmt --check
      - nix develop --command cargo-deny check
      - nix develop --command cargo clippy -- -D warnings
---
kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - pull_request
    - cron

steps:
  - name: Run tests and build
    image: nixpkgs/nix-flakes:nixos-22.05
    commands:
      - nix develop --command cargo test
      - nix build .
      - nix run . -- fcuny.net
---
kind: pipeline
type: docker
name: flakes-update
trigger:
  event:
    - cron

steps:
  - name: update flakes
    image: nixpkgs/nix-flakes:nixos-22.05
    commands:
      - nix flake update --commit-lock-file
      - nix develop -c git push origin --all
