project_name: x509-info

builds:
  - id: default
    main: .
    binary: x509-info
    flags:
      - -tags
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildDate={{ .CommitDate }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - default
    name_template: "x509-info_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"
